<div class="card">
    <h2 class="title">
        <?php echo esc_html(__('Reset links structure', 'pdp')); ?>
    </h2>

    <p>
        <?php echo esc_html(__('Do you want to reset public links to all post drafts on your website? For all types of posts, it will be generated new random link structures. The existing links generated by the PDP plugin will no longer work.', 'pdp')); ?>
    </p>
    
    <a href="#" class="button button--data-reset button-secondary">
        <?php echo esc_html(__('Reset links structure', 'pdp')); ?>
    </a>
</div>
